export const STORE_LEARNER_INFORMATION = 'STORE_LEARNER_INFORMATION';
export const REMOVE_LEARNER_INFORMATION = 'REMOVE_LEARNER_INFORMATION';

export const STORE_GRADE_LEARNER_INFORMATION = 'STORE_GRADE_LEARNER_INFORMATION';
export const REMOVE_GRADE_LEARNER_INFORMATION = 'REMOVE_LEARNER_INFORMATION';

export const STORE_CONTACT_INFORMATION = 'STORE_CONTACT_INFORMATION';
export const REMOVE_CONTACT_INFORMATION = 'REMOVE_LEARNER_INFORMATION';
